name: Mirror

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
      SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
       source-repo: "git@github.com:PHIKN1GHT/phikn1ght.github.io.git"
       destination-repo: "git@gitee.com:KALE1D0/KALE1D0.git"

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
        gitee-username: KALE1D0
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        gitee-repo: KALE1D0/KALE1D0
